"""Concatenate every shard's rows into main.csv, run the assertions, write stats.

Nobody trains until this is green. A contaminated split does not look like a
bug -- it looks like an unusually good number.
"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))  # run from anywhere

import glob

import pandas as pd

from quorum.degrade import N_VARIANTS
from quorum.embed import MANIFESTS

# Highest priority wins when the same image turns up in two sources: an eval
# copy always beats a train copy, so a duplicate can never leak into training.
PRIORITY = ["test_organizer", "test_ood", "test_wild", "calib", "train"]

files = sorted(glob.glob(str(MANIFESTS / "rows_*.csv")))
if not files:
    raise SystemExit(f"no rows_*.csv in {MANIFESTS} -- run the embedding pass first")
df = pd.concat([pd.read_csv(f) for f in files], ignore_index=True)
df = df[~df.source.str.startswith("smoke")]

# ---- dedupe: one split per image, eval wins ----
n_dupe = int((df.groupby("image_id").split.nunique() > 1).sum())
df["_p"] = df.split.map({s: i for i, s in enumerate(PRIORITY)}).fillna(99)
keep = df.sort_values("_p").groupby("image_id", sort=False).split.first()
df = df[df.split == df.image_id.map(keep)].drop(columns="_p")
df = df.drop_duplicates(subset=["image_id", "variant"])

# ---------------- ASSERTIONS: must fail loudly ----------------

# A. organizer validation quarantined
val = df[df.source == "organizer_val"]
assert len(val) > 0, "organizer val missing -- run embed_dir.py on it (see RUNBOOK 5)"
assert (val.split == "test_organizer").all(), "ORGANIZER VAL LEAKED INTO TRAINING"

# B. OOD set eval-only
assert (df[df.source == "so_fake_ood"].split == "test_ood").all(), "OOD LEAKED"

# C. calibration split trains nothing
assert (df[df.source == "sid_calib"].split == "calib").all()

# D. no image_id spans two splits (dedupe above should guarantee this)
spans = df.groupby("image_id").split.nunique()
assert (spans == 1).all(), f"{(spans > 1).sum()} image_ids span splits"

# E. class balance sane in train
tr = df[(df.split == "train") & (df.variant == "clean")]
assert 0.35 < tr.label.mean() < 0.65, f"train is {tr.label.mean():.0%} AI -- rebalance"

# F. eval images carry the whole grid (catches a shard that crashed midway)
ev = df[df.split.str.startswith("test") | (df.split == "calib")]
per = ev.groupby("image_id").variant.nunique()
bad = per[per != N_VARIANTS]
assert bad.empty, f"{len(bad)} eval images missing variants (expect {N_VARIANTS}):\n{bad.head()}"


df.to_csv(MANIFESTS / "main.csv", index=False)

clean = df[df.variant == "clean"]
FENCE = "\n```\n"
with open(MANIFESTS / "stats.md", "w") as f:
    f.write("# Manifest stats\n\n_Generated by scripts/build_manifest.py_\n")
    f.write("\n## Rows per split (clean variant only)\n")
    f.write(FENCE + pd.crosstab(clean.split, clean.label).to_string() + FENCE)
    f.write("\n## Sources\n")
    f.write(FENCE + pd.crosstab(clean.source, clean.split).to_string() + FENCE)
    f.write(f"\n## Variants\n\nGrid = {N_VARIANTS} (14 settings + clean). "
            f"Train images carry clean + sampled variants only.\n\n"
            f"Images seen in more than one split, resolved to the eval copy: {n_dupe}\n")
    f.write("\n## Assertions\n\nA-F all passed.\n")

print(f"{len(df)} rows, {df.image_id.nunique()} images -> {MANIFESTS / 'main.csv'}")
print((MANIFESTS / "stats.md").read_text())
